# Generated by Django 3.2.4 on 2021-08-14 14:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='listing',
            name='creation_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
