# Generated by Django 3.2.4 on 2021-08-16 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20210814_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('fashion', 'Fashion'), ('toys', 'Toys'), ('electronics', 'Electronics'), ('entertainment', 'Entertainment'), ('automotive', 'Automotive'), ('office', 'Office'), ('furniture', 'Furnishing'), ('others', 'Others')], max_length=64),
        ),
        migrations.AlterField(
            model_name='listing',
            name='creation_timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
