# Generated by Django 3.2.4 on 2021-12-03 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_listing_winner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['category', 'title']},
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('fashion', 'Fashion'), ('toys', 'Toys'), ('electronics', 'Electronics'), ('entertainment', 'Entertainment'), ('automotive', 'Automotive'), ('office', 'Office'), ('furniture', 'Furnishing'), ('others', 'Others')], max_length=64),
        ),
    ]
