# Generated by Django 3.2.4 on 2021-12-03 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20211203_0444'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['status', 'category', 'title']},
        ),
    ]
