# Generated by Django 3.2.4 on 2021-12-03 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20211203_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('fashion', 'Fashion'), ('food', 'Food'), ('toys', 'Toys'), ('electronics', 'Electronics'), ('entertainment', 'Entertainment'), ('automotive', 'Automotive'), ('office', 'Office'), ('furniture', 'Furnishing'), ('others', 'Others')], max_length=64),
        ),
    ]
